### ISSUE TITLE
K: Copy is really inconvenient

### ISSUE THREAD

**Issue by matthiasbeyer** [deinstapel/cursive-tabs#9]
Hi,

I find `K: Copy` really inconvenient as I cannot use `String` as `K`.

Is there a way to make the current situation better?

**Comment by jwuensche** [comment]
I can see how that leads to some really annoying inconveniences. 
We should fix that up and include it in the next minor update for cursive `0.15`. As the change will create some breaking API changes.
I'll have a look at your PR and let's see if we can find a nice solution for that.

**Comment by jwuensche** [comment]
This patch has been included with the release of `0.5`.
